definitions:
  controllers.LoginInput:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  controllers.RegisterInput:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  controllers.productCategoryInput:
    properties:
      name:
        type: string
    type: object
  models.ProductCategory:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
paths:
  /login:
    post:
      description: Logging in to get jwt token to access admin or user api by roles.
      parameters:
      - description: the body to login a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Login as as user.
      tags:
      - Auth
  /product-categories:
    get:
      description: Get a list of ProductCategory.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ProductCategory'
            type: array
      summary: Get all Product Category.
      tags:
      - ProductCategory
    post:
      description: create new Product  Category
      parameters:
      - description: the body to create new age rating category
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.productCategoryInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ProductCategory'
      security:
      - BearerToken: []
      summary: Create Product Category
      tags:
      - ProductCategory
  /product-categories/{id}:
    delete:
      description: Delete a ProductCategory by id.
      parameters:
      - description: ProductCategory id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
      summary: Delete one ProductCategory.
      tags:
      - ProductCategory
    get:
      description: Get an ProductCategory by id.
      parameters:
      - description: ProductCategory id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ProductCategory'
      summary: Get ProductCategory.
      tags:
      - ProductCategory
    patch:
      description: Update ProductCategory by id.
      parameters:
      - description: ProductCategory id
        in: path
        name: id
        required: true
        type: string
      - description: the body to update product category
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.productCategoryInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ProductCategory'
      summary: Update ProductCategory.
      tags:
      - ProductCategory
  /register:
    post:
      description: registering a user from public access.
      parameters:
      - description: the body to register a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.RegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Register a user.
      tags:
      - Auth
swagger: "2.0"
